name: telegram_bot_gratis_server
description: A Library Full Package Template
version: 0.0.0
homepage: https://github.com/azkadev/telegram_bot_gratis
repository: https://github.com/azkadev/telegram_bot_gratis
issue_tracker: https://github.com/azkadev/telegram_bot_gratis/issues 
documentation: https://youtube.com/@azkadev
funding:
  - https://github.com/sponsors/azkadev


platforms:
 android:
 ios:
 linux:
 macos:
 web:
 windows:

# topics:
#   - telegram_bot_gratis
#   - telegram_bot_gratis_flutter
#   - telegram_bot_gratis_dart
environment:
  sdk: ^3.2.3

# Add regular dependencies here.
# dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
